---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: fumos
# description will be included in the image's metadata
description: FumOS-bootc.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/cosmic-atomic-main
image-version: latest #42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  - type: dnf #packages for japanese kanji rendering instead of chinese fallback and also adding these cool things
    repos:
      cleanup: true
    install:
      install-weak-deps: false
      packages:
        - default-fonts-core-emoji
        - default-fonts
        - default-fonts-cjk-sans
        - google-noto-color-emoji-fonts
        - google-noto-emoji-fonts
        - google-noto-sans-cjk-vf-fonts
        - glibc-all-langpacks
        - langpacks-ja
        - langpacks-core-ja
        - langpacks-fonts-ja
        

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - fastfetch
        - vim
        - neovim
        - htop
        - btop
        - fcitx5-configtool
        - fcitx5-mozc
        - fcitx5-chinese-addons
        - fcitx5-gtk
        - fcitx5-hangul
        - kcm-fcitx5
        - glibc-all-langpacks
        - jetbrains-mono-fonts-all
        - ptyxis
        - firewall-config
        - kf6-kirigami
        - qt6ct
        - plasma-breeze
        - kf6-qqc2-desktop-style
        - ptyxis
        - libappindicator-gtk3
        - libindicator
        - p7zip
        - p7zip-plugins
        - unar
        - distrobox
        
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: dnf
    install:
      packages:
        - libvirt-daemon-kvm
        - libvirt-client
        - virt-install
        - virt-manager
        - qemu-kvm
        - dnsmasq
        # Optional: useful for networking
        - bridge-utils
        - virt-viewer

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly


  - type: containerfile
    snippets:
      - RUN flatpak config --set languages "en;ja"
      - RUN systemctl enable virtqemud \
                   virtnetworkd \
                   virtstoraged \
                   virtproxyd

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - io.gitlab.librewolf-community
          - com.brave.Browser
          - io.mpv.Mpv
          - org.onlyoffice.desktopeditors
          - com.ranfdev.DistroShelf
          - com.obsproject.Studio
          - com.obsproject.Studio.Plugin.GStreamerVaapi
          - com.obsproject.Studio.Plugin.Gstreamer
          - com.obsproject.Studio.Plugin.OBSVkCapture
          - org.freedesktop.Platform.VulkanLayer.OBSVkCapture
          - org.freedesktop.Platform.VulkanLayer.vkBasalt
          - com.github.tchx84.Flatseal
          - com.discordapp.Discord
          - com.github.Matoking.protontricks
          - com.vysp3r.ProtonPlus
          - io.github.flattool.Warehouse
          - org.qbittorrent.qBittorrent
          
  
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - type: os-release
    properties:
      ID: fumos
      ID_LIKE: fedora
      NAME: FumOS
      VERSION: Cirno
      PRETTY_NAME: FumOS
      DEFAULT_HOSTNAME: FumOS
      VERSION_CODENAME: Cirno
      
  # swap kernel
  - type: script
    scripts:
      - swap-kernel.sh
      - initramfs.sh

  

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
